//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertViewerVS.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CertViewerVS.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Certificate File.
        /// </summary>
        internal static string DialogTitle_OpenCertificateFile
        {
            get
            {
                return ResourceManager.GetString("DialogTitle_OpenCertificateFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        internal static string Error_Occurred
        {
            get
            {
                return ResourceManager.GetString("Error_Occurred", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string Filter_AllFiles
        {
            get
            {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Certificate Files.
        /// </summary>
        internal static string Filter_CertificateFiles
        {
            get
            {
                return ResourceManager.GetString("Filter_CertificateFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password was incorrect. Would you like to try again?.
        /// </summary>
        internal static string Prompt_IncorrectPasswordRetry
        {
            get
            {
                return ResourceManager.GetString("Prompt_IncorrectPasswordRetry", resourceCulture);
            }
        }
    }
}
